name: CI/CD HTML + Nginx

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. نسخ الكود من GitHub
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. تسجيل الدخول إلى Docker Hub باستخدام GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. بناء صورة Docker
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cka-demo:latest .

    # 4. رفع الصورة إلى Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/cka-demo:latest

    # 5. نشر على Kubernetes (Minikube أو Cluster بعيد)
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/cka-demo cka-demo=${{ secrets.DOCKER_USERNAME }}/cka-demo:latest
        kubectl rollout status deployment/cka-demo
